name: Publish dev
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
jobs:
  npm-publish:
    name: npm publish
    strategy:
      fail-fast: false
      matrix:
        include:
          - package: '@sirh/discord-http-webserver'
            folder: './'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    if: github.repository_owner == 'OfficialSirH'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Check the current development version
        id: release-check
        run: |
          if [[ $(npm view ${{ matrix.package }}@dev version | grep -e "$(git rev-parse --short HEAD)") ]]; \
            then echo "RELEASE=0" >> "$GITHUB_OUTPUT"; \
            else echo "RELEASE=1" >> "$GITHUB_OUTPUT"; \
          fi

      - name: Install dependencies
        if: steps.release-check.outputs.release == '1'
        uses: ./actions/yarn-cache

      - name: Build dependencies
        if: steps.release-check.outputs.release == '1'
        run: yarn run build

      - name: Publish package
        if: steps.release-check.outputs.release == '1'
        run: |
          yarn run release --preid "dev.$(date +%s)-$(git rev-parse --short HEAD)"
          npm publish --no-git-checks --tag dev || true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Deprecate prior development releases
        if: steps.release-check.outputs.release == '1'
        run: yarn exec npm-deprecate --name "*dev*" --message "This version is deprecated. Please use a newer version." --package ${{ matrix.package }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
